# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/www" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/e2e" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/FT_functions/functions" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/FT_functions/compiler" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/cloud_actions/functions" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/cloud_build_functions/functions" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/cloud_functions/functions" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "dependencies"
